/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Funciones.EditarFicheros;
import Funciones.StructParametros;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Lyoko
 */
public class jConfig extends javax.swing.JInternalFrame {

    /**
     * Creates new form jConfig
     */
    private EditarFicheros edit;
    StructParametros p;
    JFileChooser fc;

    public jConfig(StructParametros p) {
        initComponents();
        edit = new EditarFicheros();
        this.p = p;
        jruta.setText(p.getRuta());
        jrutaresultado.setText(p.getResultado());
        this.fc = new JFileChooser();//Creamos el objeto JFileChooser
        jLabel2.setVisible(false);
        jCBIdioma.setVisible(false);
        jrutaCartas.setText(p.getImgCartas());
        jrutaincentivo.setText(p.getGana());
        jrutaincentivo1.setText(p.getPierde());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jCBIdioma = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jruta = new javax.swing.JTextField();
        jBMazoA = new javax.swing.JButton();
        jBMazoB = new javax.swing.JButton();
        jBMazoC = new javax.swing.JButton();
        jBMazoD = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBIntrucciones = new javax.swing.JButton();
        jAceptar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jrutaresultado = new javax.swing.JTextField();
        jBExaminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jrutaCartas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jrutaincentivo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jrutaincentivo1 = new javax.swing.JTextField();

        setTitle("Ajustes del programa");

        jLabel2.setText("Idioma");

        jCBIdioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Ruta de ficheros para cartas:");

        jBMazoA.setText("Mazo A");
        jBMazoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMazoAActionPerformed(evt);
            }
        });

        jBMazoB.setText("Mazo B");
        jBMazoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMazoBActionPerformed(evt);
            }
        });

        jBMazoC.setText("Mazo C");
        jBMazoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMazoCActionPerformed(evt);
            }
        });

        jBMazoD.setText("Mazo D");
        jBMazoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMazoDActionPerformed(evt);
            }
        });

        jLabel4.setText("Editar barajas:");

        jBIntrucciones.setText("Editar Instrucciones");
        jBIntrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIntruccionesActionPerformed(evt);
            }
        });

        jAceptar.setText("Aceptar");
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre de resultado:");

        jBExaminar.setText("...");
        jBExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExaminarActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre de imagen las cartas:");

        jLabel7.setText("Nombre de imagen incentivo: ");

        jLabel1.setText("La imagenes deben estar en la ruta: src/Imagenes");

        jLabel8.setText("Cuando GANA");

        jLabel9.setText("Cuando PIERDE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jruta, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(294, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrutaCartas, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addComponent(jBIntrucciones)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrutaresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBMazoA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBMazoB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(jAceptar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCancelar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBMazoC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBMazoD))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrutaincentivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrutaincentivo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBExaminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jrutaCartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jrutaincentivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jrutaincentivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jrutaresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jBMazoA)
                    .addComponent(jBMazoB)
                    .addComponent(jBMazoC)
                    .addComponent(jBMazoD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBIntrucciones)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAceptar)
                    .addComponent(jCancelar))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBMazoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMazoAActionPerformed
        edit.EditarFicheroXML(p.getRuta() + "/BarajaA.xml");
    }//GEN-LAST:event_jBMazoAActionPerformed

    private void jBMazoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMazoBActionPerformed
        edit.EditarFicheroXML(p.getRuta() + "/BarajaB.xml");
    }//GEN-LAST:event_jBMazoBActionPerformed

    private void jBMazoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMazoCActionPerformed
        edit.EditarFicheroXML(p.getRuta() + "/BarajaC.xml");
    }//GEN-LAST:event_jBMazoCActionPerformed

    private void jBMazoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMazoDActionPerformed
        edit.EditarFicheroXML(p.getRuta() + "/BarajaD.xml");
    }//GEN-LAST:event_jBMazoDActionPerformed

    private void jBIntruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIntruccionesActionPerformed
        edit.EditarFicheroTXT("src/Recursos/Instrucciones.txt");
    }//GEN-LAST:event_jBIntruccionesActionPerformed

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        p.setRuta(jruta.getText());
        p.setResultado(jrutaresultado.getText());
        p.setImgCartas(jrutaCartas.getText());
        p.setGana(jrutaincentivo.getText());
        p.setPierde(jrutaincentivo1.getText());      
        dispose();
    }//GEN-LAST:event_jAceptarActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        dispose();

    }//GEN-LAST:event_jCancelarActionPerformed

    private void jBExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExaminarActionPerformed
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);//Indicamos lo que podemos seleccionar
        //FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT", "txt");//Creamos el filtro
        //fc.setFileFilter(filtro);//Le indicamos el filtro
        int seleccion = fc.showOpenDialog(this);//Abrimos la ventana, guardamos la opcion seleccionada por el usuario   
        if (seleccion == JFileChooser.APPROVE_OPTION) {//Si el usuario, pincha en aceptar  
            File fichero = fc.getSelectedFile();//Seleccionamos el fichero
            jruta.setText(fichero.getAbsolutePath());//Ecribe la ruta del fichero seleccionado en el campo de texto
        }
    }//GEN-LAST:event_jBExaminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JButton jBExaminar;
    private javax.swing.JButton jBIntrucciones;
    private javax.swing.JButton jBMazoA;
    private javax.swing.JButton jBMazoB;
    private javax.swing.JButton jBMazoC;
    private javax.swing.JButton jBMazoD;
    private javax.swing.JComboBox<String> jCBIdioma;
    private javax.swing.JButton jCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jruta;
    private javax.swing.JTextField jrutaCartas;
    private javax.swing.JTextField jrutaincentivo;
    private javax.swing.JTextField jrutaincentivo1;
    private javax.swing.JTextField jrutaresultado;
    // End of variables declaration//GEN-END:variables
}
