/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Funciones.StructParametros;

/**
 *
 * @author Lyoko
 */
public class jParametros extends javax.swing.JInternalFrame {

    /**
     * Creates new form Parametros
     */
    StructParametros p;
    String memoria, nuevo;

    public jParametros(StructParametros p) {
        initComponents();
        this.p = p;
        jSaldoini.setValue(p.getSaldoini());
        jSaldo.setSelected(p.isVersaldo());
        jNjugada.setValue(p.getNumjugadas());
        jprestamo.setValue(p.getPrestamo());
        jInvjuego.setSelected(p.isInvjuego());
        jInvorden.setSelected(p.isInvorden());
        jColocacion.setText(p.getColocar());
        jretardo.setValue(p.getRetardo());
        jveretardo.setSelected(p.isVeretardo());
        jgambling.setValue(p.getGambling());
        jsonido.setSelected(p.isSonido());
        memoria = jColocacion.getText();
        jcorrecto.setVisible(false);
        jSaldoganado.setSelected(p.isSaldoganado());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jInvjuego = new javax.swing.JCheckBox();
        jInvorden = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jColocacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jveretardo = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jSaldoini = new javax.swing.JSpinner();
        jSaldo = new javax.swing.JCheckBox();
        jNjugada = new javax.swing.JSpinner();
        jprestamo = new javax.swing.JSpinner();
        jretardo = new javax.swing.JSpinner();
        jgambling = new javax.swing.JSpinner();
        jAceptar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jsonido = new javax.swing.JCheckBox();
        jcorrecto = new javax.swing.JLabel();
        jSaldoganado = new javax.swing.JCheckBox();

        setTitle("Parametros de la partida");

        jLabel5.setText("Saldo inicial:");

        jLabel7.setText("Nº de jugadas:");

        jLabel8.setText("Préstamo si saldo negativo:");

        jInvjuego.setText("Invertir el juego");

        jInvorden.setText("Invertir orden");

        jLabel9.setText("Colocación:");

        jColocacion.setText("ABCD");
        jColocacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jColocacionFocusLost(evt);
            }
        });
        jColocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColocacionActionPerformed(evt);
            }
        });

        jLabel10.setText("Retardo para ocultar la carta:");

        jveretardo.setSelected(true);
        jveretardo.setText("Mostrar retardo");

        jLabel11.setText("Gambling parcial:");

        jSaldo.setSelected(true);
        jSaldo.setText("Saldo visible");

        jAceptar.setText("Aceptar");
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });

        jsonido.setSelected(true);
        jsonido.setText("Activar sonido");

        jcorrecto.setText("Limite 4 mazos no repetidos.");

        jSaldoganado.setSelected(true);
        jSaldoganado.setText("Saldo ganado en la partida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jretardo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jveretardo)
                            .addComponent(jSaldo)
                            .addComponent(jInvjuego)
                            .addComponent(jInvorden)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jgambling, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(jSaldoini, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNjugada, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jColocacion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcorrecto))
                            .addComponent(jsonido)
                            .addComponent(jSaldoganado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jAceptar)
                        .addGap(71, 71, 71)
                        .addComponent(jCancelar)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSaldoini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jNjugada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInvjuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInvorden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jColocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcorrecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jretardo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jveretardo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jgambling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsonido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSaldoganado)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAceptar)
                    .addComponent(jCancelar))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        if (comprobarColocacion()) {
            p.setSaldoini((int) jSaldoini.getValue());
            p.setVersaldo(jSaldo.isSelected());
            p.setNumjugadas((int) jNjugada.getValue());
            p.setPrestamo((int) jprestamo.getValue());
            p.setInvjuego(jInvjuego.isSelected());
            p.setInvorden(jInvorden.isSelected());
            p.setColocar(jColocacion.getText());
            p.setRetardo((int) jretardo.getValue());
            p.setVeretardo(jveretardo.isSelected());
            p.setGambling((int) jgambling.getValue());
            p.setSonido(jsonido.isSelected());
            p.setSaldoganado(jSaldoganado.isSelected());
            dispose();
        }
    }//GEN-LAST:event_jAceptarActionPerformed

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        dispose();

    }//GEN-LAST:event_jCancelarActionPerformed

    private void jColocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColocacionActionPerformed
        comprobarColocacion();
    }//GEN-LAST:event_jColocacionActionPerformed

    private void jColocacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jColocacionFocusLost
        comprobarColocacion();
    }//GEN-LAST:event_jColocacionFocusLost

    boolean comprobarColocacion() {
        boolean nice;
        nuevo = jColocacion.getText();
        if (nuevo.length() <= 5) {
            int correcto = 0;
            for (int i = 0; i < nuevo.length(); i++) {
                switch (nuevo.charAt(i)) {
                    case 'A':
                    case 'a':
                        correcto++;
                        break;
                    case 'B':
                    case 'b':
                        correcto++;
                        break;
                    case 'C':
                    case 'c':
                        correcto++;
                        break;
                    case 'D':
                    case 'd':
                        correcto++;
                        break;
                }
            }
            if (nuevo.length() != correcto) {
                jColocacion.setText(p.getColocar());
                jcorrecto.setVisible(true);
                nice = false;
            } else {
                jcorrecto.setVisible(false);
                nice = true;
            }
        } else {
            jColocacion.setText(p.getColocar());
            jcorrecto.setVisible(true);
            nice = false;
        }

        memoria = jColocacion.getText();
        return nice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JButton jCancelar;
    private javax.swing.JTextField jColocacion;
    private javax.swing.JCheckBox jInvjuego;
    private javax.swing.JCheckBox jInvorden;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jNjugada;
    private javax.swing.JCheckBox jSaldo;
    private javax.swing.JCheckBox jSaldoganado;
    private javax.swing.JSpinner jSaldoini;
    private javax.swing.JLabel jcorrecto;
    private javax.swing.JSpinner jgambling;
    private javax.swing.JSpinner jprestamo;
    private javax.swing.JSpinner jretardo;
    private javax.swing.JCheckBox jsonido;
    private javax.swing.JCheckBox jveretardo;
    // End of variables declaration//GEN-END:variables
}
