/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Funciones.IU;
import Funciones.Juego;
import java.awt.CardLayout;

/**
 *
 * @author Lyoko
 */
public class jPartida extends javax.swing.JInternalFrame {

    /**
     * Creates new form jPartida
     */
    public jPartida() {
        initComponents();
        juego = new Juego();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnMazoA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Partida en marcha");

        jBtnMazoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reverso2.JPG"))); // NOI18N
        jBtnMazoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMazoAActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reverso2.JPG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnMazoA, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnMazoA, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(424, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnMazoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMazoAActionPerformed
        JugarMazo('A');
    }//GEN-LAST:event_jBtnMazoAActionPerformed

    /**
     * Funcion que levanta la carta superior de uno de los mazos
     *
     * @param mazo
     */
    private void JugarMazo(char mazo) {

        // Si el estado no es activo, no juega el mazo.
        if (estado != 2) {
            return;
        }
        CambiaEstado(1);

        if (juego.jugarMazo(mazo) == 0) {
            // Mostrar resultado de la carta
            switch (mazo) {
                case 'A':
                case 'a':
                    jBtnMazoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("../Imagenes/anverso2.jpg")));
                    jBtnMazoA.setText("<html><body>Gana:<br>" + String.valueOf(juego.getCarta(mazo).getGanancia()) + "€" + "<br><br>Pierde:<br>" + String.valueOf(juego.getCarta(mazo).getPerdida()) + "€</body></html>");
                    break;
                case 'B':
                case 'b':
                    jLAnversoB.setText("<html><body>Gana:<br>" + String.valueOf(juego.getCarta(mazo).getGanancia()) + "€" + "<br><br>Pierde:<br>" + String.valueOf(juego.getCarta(mazo).getPerdida()) + "€</body></html>");
                    lb.show(jPMazoB0, getJPAnversoB().getName());
                    break;
                case 'C':
                case 'c':
                    jLAnversoC.setText("<html><body>Gana:<br>" + String.valueOf(juego.getCarta(mazo).getGanancia()) + "€" + "<br><br>Pierde:<br>" + String.valueOf(juego.getCarta(mazo).getPerdida()) + "€</body></html>");
                    lc.show(jPMazoC0, getJPAnversoC().getName());
                    break;
                case 'D':
                case 'd':
                    jLAnversoD.setText("<html><body>Gana:<br>" + String.valueOf(juego.getCarta(mazo).getGanancia()) + "€" + "<br><br>Pierde:<br>" + String.valueOf(juego.getCarta(mazo).getPerdida()) + "€</body></html>");
                    ld.show(jPMazoD0, getJPAnversoD().getName());
                    break;
            }
            // Actualizar ganancias
            jTFGanancias.setText(String.valueOf(juego.getSaldo()) + " €");
            jTFGanancias.repaint();
        } else {
            switch (mazo) {
                case 'A':
                case 'a':
                    jPMazoA0.setVisible(false);
                    break;
                case 'B':
                case 'b':
                    jPMazoB0.setVisible(false);
                    break;
                case 'C':
                case 'c':
                    jPMazoC0.setVisible(false);
                    break;
                case 'D':
                case 'd':
                    jPMazoD0.setVisible(false);
                    break;
            }
        }
        //repaint();
        //new IU.HabilitarMazo ('A').start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnMazoA;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private Juego juego;
}
