/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Funciones.Juego;
import Funciones.StructParametros;
import java.awt.Frame;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lyoko
 */
public class MainMesa extends javax.swing.JFrame {

    /**
     * Creates new form MainMesa
     */
    
    jPartida partida; //ventana juego
    public Juego juego; 
    jParametros param; //ventana parametros
    StructParametros parametros; //Parametros
    jConfig config;
    int numPartidas;

    public MainMesa() {
        //parametros por defecto
        parametros= new StructParametros("src/Datos", 2000, true, 100, 200, false, false, "ABCD",3 ,true ,20,true,"Resultado", true,"../Imagenes/","reverso2.png","dinero.png","vacio.png");
        //partida = new jPartida(parametros);
        param = new jParametros(parametros);
        config = new jConfig(parametros);
        numPartidas=0;
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Imagenes/joker.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMEjecucion = new javax.swing.JMenu();
        jMEjecutar = new javax.swing.JMenuItem();
        jMDetener = new javax.swing.JMenuItem();
        jMExprerimento = new javax.swing.JMenu();
        jMAjustes = new javax.swing.JMenuItem();
        jMParametros = new javax.swing.JMenuItem();
        jMAyuda = new javax.swing.JMenu();
        jMContenido = new javax.swing.JMenuItem();
        jMAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Joker");

        jMEjecucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/partida.png"))); // NOI18N
        jMEjecucion.setText("Partida");

        jMEjecutar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/play.png"))); // NOI18N
        jMEjecutar.setText("Ejecutar");
        jMEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEjecutarActionPerformed(evt);
            }
        });
        jMEjecucion.add(jMEjecutar);

        jMDetener.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMDetener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stop.png"))); // NOI18N
        jMDetener.setText("Detener");
        jMDetener.setEnabled(false);
        jMDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDetenerActionPerformed(evt);
            }
        });
        jMEjecucion.add(jMDetener);

        menuBar.add(jMEjecucion);

        jMExprerimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config.png"))); // NOI18N
        jMExprerimento.setText("Configuración");

        jMAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/option.png"))); // NOI18N
        jMAjustes.setText("Ajustes de programa");
        jMAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAjustesActionPerformed(evt);
            }
        });
        jMExprerimento.add(jMAjustes);

        jMParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mazo.png"))); // NOI18N
        jMParametros.setText("Parametros de la partida");
        jMParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMParametrosActionPerformed(evt);
            }
        });
        jMExprerimento.add(jMParametros);

        menuBar.add(jMExprerimento);

        jMAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/about.png"))); // NOI18N
        jMAyuda.setMnemonic('h');
        jMAyuda.setText("Ayuda");

        jMContenido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMContenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.png"))); // NOI18N
        jMContenido.setMnemonic('c');
        jMContenido.setText("Contenidos");
        jMContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMContenidoActionPerformed(evt);
            }
        });
        jMAyuda.add(jMContenido);

        jMAcercade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMAcercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/write.png"))); // NOI18N
        jMAcercade.setMnemonic('a');
        jMAcercade.setText("Acerca de");
        jMAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAcercadeActionPerformed(evt);
            }
        });
        jMAyuda.add(jMAcercade);

        menuBar.add(jMAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMContenidoActionPerformed
        jFContenido jfc = new jFContenido();
        jfc.setVisible(true);
        jfc.setSize(900, 800);
    }//GEN-LAST:event_jMContenidoActionPerformed

    private void jMParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMParametrosActionPerformed
        Escritorio.add(param);
        param.toFront();
        try {
            param.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMesa.class.getName()).log(Level.SEVERE, null, ex);
        }
        param.show();

    }//GEN-LAST:event_jMParametrosActionPerformed

    private void jMAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAcercadeActionPerformed
        jAcerca acerca = new jAcerca(this, rootPaneCheckingEnabled);
        acerca.setVisible(true);
    }//GEN-LAST:event_jMAcercadeActionPerformed

    private void jMDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDetenerActionPerformed
        jMDetener.setEnabled(false);
        jMEjecutar.setEnabled(true);
        jMParametros.setEnabled(true);
        jMAjustes.setEnabled(true);
        juego= partida.getJuego();
        juego.grabaResultado(parametros.getResultado(),numPartidas);
        System.out.println(parametros.getResultado());
        partida.CambiaEstado(0);
        partida.CambiaEstado(2);
        partida.dispose();
        
    }//GEN-LAST:event_jMDetenerActionPerformed

    private void jMEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEjecutarActionPerformed
        jMDetener.setEnabled(true);
        jMEjecutar.setEnabled(false);
        jMParametros.setEnabled(false);
        jMAjustes.setEnabled(false);
        numPartidas++;
        partida = new jPartida(parametros);
        Escritorio.add(partida);
        partida.toFront();
        try {
            partida.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMesa.class.getName()).log(Level.SEVERE, null, ex);
        }
        partida.show();

        //Ventana de instruciones
        Frame f = JOptionPane.getFrameForComponent(this);
        jInstruciones dialog = new jInstruciones(f, true);
        dialog.show();

    }//GEN-LAST:event_jMEjecutarActionPerformed

    private void jMAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAjustesActionPerformed
        Escritorio.add(config);
        config.toFront();
        try {
            config.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMesa.class.getName()).log(Level.SEVERE, null, ex);
        }
        config.show();
    }//GEN-LAST:event_jMAjustesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMesa main = new MainMesa();
                main.setExtendedState(MAXIMIZED_BOTH);
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem jMAcercade;
    private javax.swing.JMenuItem jMAjustes;
    private javax.swing.JMenu jMAyuda;
    private javax.swing.JMenuItem jMContenido;
    private javax.swing.JMenuItem jMDetener;
    private javax.swing.JMenu jMEjecucion;
    private javax.swing.JMenuItem jMEjecutar;
    private javax.swing.JMenu jMExprerimento;
    private javax.swing.JMenuItem jMParametros;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
