/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Funciones.EditarFicheros;

/**
 *
 * @author Lyoko
 */
public class MainMesa extends javax.swing.JFrame {

    /**
     * Creates new form MainMesa
     */
   
    private EditarFicheros edit;
    jPartida parti;
    
    public MainMesa() {
        edit = new EditarFicheros();
        parti = new jPartida();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMExprerimento = new javax.swing.JMenu();
        jMParametros = new javax.swing.JMenuItem();
        jMBaraja = new javax.swing.JMenu();
        jMBarajaA = new javax.swing.JMenuItem();
        jMBarajaB = new javax.swing.JMenuItem();
        jMBarajaC = new javax.swing.JMenuItem();
        jMBarajaD = new javax.swing.JMenuItem();
        jMRepartir = new javax.swing.JMenuItem();
        jMIntrucciones = new javax.swing.JMenuItem();
        jMEjecucion = new javax.swing.JMenu();
        jMEjecutar = new javax.swing.JMenuItem();
        jMDetener = new javax.swing.JMenuItem();
        jMAyuda = new javax.swing.JMenu();
        jMContenido = new javax.swing.JMenuItem();
        jMAcercade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Joker");

        jMExprerimento.setText("Experimento");

        jMParametros.setText("Parametros");
        jMParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMParametrosActionPerformed(evt);
            }
        });
        jMExprerimento.add(jMParametros);

        jMBaraja.setText("Editar Baraja");

        jMBarajaA.setText("Baraja A");
        jMBarajaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBarajaAActionPerformed(evt);
            }
        });
        jMBaraja.add(jMBarajaA);

        jMBarajaB.setText("Baraja B");
        jMBarajaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBarajaBActionPerformed(evt);
            }
        });
        jMBaraja.add(jMBarajaB);

        jMBarajaC.setText("Baraja C");
        jMBarajaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBarajaCActionPerformed(evt);
            }
        });
        jMBaraja.add(jMBarajaC);

        jMBarajaD.setText("Baraja D");
        jMBarajaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMBarajaDActionPerformed(evt);
            }
        });
        jMBaraja.add(jMBarajaD);

        jMRepartir.setText("Repartir");
        jMRepartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMRepartirActionPerformed(evt);
            }
        });
        jMBaraja.add(jMRepartir);

        jMExprerimento.add(jMBaraja);

        jMIntrucciones.setText("Editar Instrucciones");
        jMIntrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIntruccionesActionPerformed(evt);
            }
        });
        jMExprerimento.add(jMIntrucciones);

        menuBar.add(jMExprerimento);

        jMEjecucion.setText("Ejecución");

        jMEjecutar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMEjecutar.setText("Ejecutar");
        jMEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEjecutarActionPerformed(evt);
            }
        });
        jMEjecucion.add(jMEjecutar);

        jMDetener.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMDetener.setText("Detener");
        jMDetener.setEnabled(false);
        jMDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDetenerActionPerformed(evt);
            }
        });
        jMEjecucion.add(jMDetener);

        menuBar.add(jMEjecucion);

        jMAyuda.setMnemonic('h');
        jMAyuda.setText("Ayuda");

        jMContenido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMContenido.setMnemonic('c');
        jMContenido.setText("Contenidos");
        jMContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMContenidoActionPerformed(evt);
            }
        });
        jMAyuda.add(jMContenido);

        jMAcercade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMAcercade.setMnemonic('a');
        jMAcercade.setText("Acerca de");
        jMAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAcercadeActionPerformed(evt);
            }
        });
        jMAyuda.add(jMAcercade);

        menuBar.add(jMAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMContenidoActionPerformed
		jFContenido jfc = new jFContenido();
                jfc.setVisible(true); 
                jfc.setSize(900,500);
    }//GEN-LAST:event_jMContenidoActionPerformed

    private void jMParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMParametrosActionPerformed

    private void jMBarajaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBarajaAActionPerformed
        edit.EditarFicheroXML ("src/Datos/BarajaA.xml");
    }//GEN-LAST:event_jMBarajaAActionPerformed

    private void jMBarajaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBarajaBActionPerformed
        edit.EditarFicheroXML ("src/Datos/BarajaB.xml");
    }//GEN-LAST:event_jMBarajaBActionPerformed

    private void jMBarajaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBarajaCActionPerformed
        edit.EditarFicheroXML ("src/Datos/BarajaC.xml");
    }//GEN-LAST:event_jMBarajaCActionPerformed

    private void jMBarajaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMBarajaDActionPerformed
        edit.EditarFicheroXML ("src/Datos/BarajaD.xml");
    }//GEN-LAST:event_jMBarajaDActionPerformed

    private void jMRepartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMRepartirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMRepartirActionPerformed

    private void jMIntruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIntruccionesActionPerformed
        edit.EditarFicheroTXT ("src/Recursos/Instrucciones.txt");
    }//GEN-LAST:event_jMIntruccionesActionPerformed

    private void jMAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAcercadeActionPerformed
        jAcerca acerca = new jAcerca(this, rootPaneCheckingEnabled);
        acerca.setVisible(true);
    }//GEN-LAST:event_jMAcercadeActionPerformed

    private void jMDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDetenerActionPerformed
        jMDetener.setEnabled(false);
        jMEjecutar.setEnabled(true);
        parti.dispose();
    }//GEN-LAST:event_jMDetenerActionPerformed

    private void jMEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEjecutarActionPerformed
        jMDetener.setEnabled(true);
        jMEjecutar.setEnabled(false);
        Escritorio.add(parti);
        parti.toFront();
        parti.show();
    }//GEN-LAST:event_jMEjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem jMAcercade;
    private javax.swing.JMenu jMAyuda;
    private javax.swing.JMenu jMBaraja;
    private javax.swing.JMenuItem jMBarajaA;
    private javax.swing.JMenuItem jMBarajaB;
    private javax.swing.JMenuItem jMBarajaC;
    private javax.swing.JMenuItem jMBarajaD;
    private javax.swing.JMenuItem jMContenido;
    private javax.swing.JMenuItem jMDetener;
    private javax.swing.JMenu jMEjecucion;
    private javax.swing.JMenuItem jMEjecutar;
    private javax.swing.JMenu jMExprerimento;
    private javax.swing.JMenuItem jMIntrucciones;
    private javax.swing.JMenuItem jMParametros;
    private javax.swing.JMenuItem jMRepartir;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
